### ISSUE TITLE
maxima 5.47 upgrade seems to break sagemath 9.5, 9.6 and 9.7

### ISSUE THREAD

**Issue by videlec** [conda-forge/maxima-feedstock#33]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In the following environment
```
$ micromamba install sagelib=9.6 maxima sympy ipywidgets
```
sage is not able to call maxima
```
$ sage -c 'assume(x >= 0)'
Traceback (most recent call last):
  File "/home/vincent/micromamba/envs/test/bin/sage-eval", line 10, in <module>
    eval(compile(s,'<cmdline>','exec'))
  File "<cmdline>", line 1, in <module>
  File "/home/vincent/micromamba/envs/test/lib/python3.10/site-packages/sage/symbolic/assumptions.py", line 676, in assume
    x.assume()
  File "sage/symbolic/expression.pyx", line 2376, in sage.symbolic.expression.Expression.assume (build/cythonized/sage/symbolic/expression.cpp:42455)
  File "sage/symbolic/expression.pyx", line 2452, in sage.symbolic.expression.Expression._maxima_init_assume_ (build/cythonized/sage/symbolic/expression.cpp:43209)
  File "sage/misc/lazy_import.pyx", line 359, in sage.misc.lazy_import.LazyImport.__getattr__ (build/cythonized/sage/misc/lazy_import.c:4166)
  File "sage/misc/lazy_import.pyx", line 217, in sage.misc.lazy_import.LazyImport.get_object (build/cythonized/sage/misc/lazy_import.c:2677)
  File "sage/misc/lazy_import.pyx", line 253, in sage.misc.lazy_import.LazyImport._get_object (build/cythonized/sage/misc/lazy_import.c:3000)
  File "/home/vincent/micromamba/envs/test/lib/python3.10/site-packages/sage/interfaces/maxima_lib.py", line 185, in <module>
    ecl_eval("#$%s$"%l)
  File "sage/libs/ecl.pyx", line 1358, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:11009)
  File "sage/libs/ecl.pyx", line 1381, in sage.libs.ecl.ecl_eval (build/cythonized/sage/libs/ecl.c:10942)
  File "sage/libs/ecl.pyx", line 327, in sage.libs.ecl.ecl_safe_eval (build/cythonized/sage/libs/ecl.c:5724)
RuntimeError: ECL says: The variable %E-VAL is unbound.
```

### Installed packages

```shell
Name                       Version       Build                Channel    
─────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex              0.1           conda_forge          conda-forge
  _openmp_mutex              4.5           2_gnu                conda-forge
  arb                        2.23.0        h44d021b_0           conda-forge
  arpack                     3.8.0         nompi_h0baa96a_101   conda-forge
  backcall                   0.2.0         pyh9f0ad1d_0         conda-forge
  bdw-gc                     8.0.6         h4bd325d_0           conda-forge
  bzip2                      1.0.8         hd590300_5           conda-forge
  c-ares                     1.23.0        hd590300_0           conda-forge
  ca-certificates            2023.11.17    hbcca054_0           conda-forge
  cddlib                     1!0.94m       h9202a9a_0           conda-forge
  cliquer                    1.22          h36c2ea0_0           conda-forge
  comm                       0.1.4         pyhd8ed1ab_0         conda-forge
  cypari2                    2.1.3         py310h75a4d73_0      conda-forge
  cysignals                  1.11.2        py310h15010d2_0      conda-forge
  cython                     0.29.36       py310hc6cd4ac_1      conda-forge
  decorator                  5.1.1         pyhd8ed1ab_0         conda-forge
  ecl                        21.2.1        h9d73b02_2           conda-forge
  eclib                      20220621      h87840bb_1           conda-forge
  ecm                        7.0.4         h9202a9a_1002        conda-forge
  expat                      2.5.0         hcb278e6_1           conda-forge
  fflas-ffpack               2.4.3         h912ac81_2           conda-forge
  font-ttf-dejavu-sans-mono  2.37          hab24e00_0           conda-forge
  font-ttf-inconsolata       3.000         h77eed37_0           conda-forge
  font-ttf-source-code-pro   2.038         h77eed37_0           conda-forge
  font-ttf-ubuntu            0.83          h77eed37_1           conda-forge
  fontconfig                 2.14.2        h14ed4e7_0           conda-forge
  fonts-conda-ecosystem      1             0                    conda-forge
  fonts-conda-forge          1             0                    conda-forge
  freetype                   2.12.1        h267a509_2           conda-forge
  future                     0.18.3        pyhd8ed1ab_0         conda-forge
  gap-core                   4.11.1        he9a28a4_5           conda-forge
  gf2x                       1.3.0         ha476b99_2           conda-forge
  giac                       1.6.0.47      he9ede01_6           conda-forge
  giflib                     5.2.1         h0b41bf4_3           conda-forge
  givaro                     4.1.1         h192cbe9_1           conda-forge
  glpk                       5.0           h445213a_0           conda-forge
  gmp                        6.3.0         h59595ed_0           conda-forge
  gmpy2                      2.1.2         py310h3ec546c_1      conda-forge
  gsl                        2.7           he838d99_0           conda-forge
  icu                        73.2          h59595ed_0           conda-forge
  igraph                     0.10.8        h52253d4_1           conda-forge
  iml                        1.0.5         hd75c201_1003        conda-forge
  ipython                    7.33.0        py310hff52083_0      conda-forge
  ipywidgets                 8.1.1         pyhd8ed1ab_0         conda-forge
  jedi                       0.19.1        pyhd8ed1ab_0         conda-forge
  jinja2                     3.0.3         pyhd8ed1ab_0         conda-forge
  jupyter_core               4.12.0        py310hff52083_0      conda-forge
  jupyterlab_widgets         3.0.9         pyhd8ed1ab_0         conda-forge
  keyutils                   1.6.1         h166bdaf_0           conda-forge
  krb5                       1.21.2        h659d440_0           conda-forge
  lcalc                      2.0.5         h8cd7e2e_0           conda-forge
  ld_impl_linux-64           2.40          h41732ed_0           conda-forge
  lerc                       4.0.0         h27087fc_0           conda-forge
  libblas                    3.9.0         20_linux64_openblas  conda-forge
  libbraiding                1.1           h58526e2_0           conda-forge
  libbrial                   1.2.12        h3155cbd_1           conda-forge
  libcblas                   3.9.0         20_linux64_openblas  conda-forge
  libcurl                    8.5.0         hca28451_0           conda-forge
  libdeflate                 1.19          hd590300_0           conda-forge
  libedit                    3.1.20191231  he28a2e2_2           conda-forge
  libev                      4.33          h516909a_1           conda-forge
  libexpat                   2.5.0         hcb278e6_1           conda-forge
  libffi                     3.4.2         h7f98852_5           conda-forge
  libflint                   2.9.0         h2f819a4_ntl_100     conda-forge
  libgcc-ng                  13.2.0        h807b86a_3           conda-forge
  libgd                      2.3.3         h119a65a_9           conda-forge
  libgfortran-ng             13.2.0        h69a702a_3           conda-forge
  libgfortran5               13.2.0        ha4646dd_3           conda-forge
  libgomp                    13.2.0        h807b86a_3           conda-forge
  libhomfly                  1.02r6        h36c2ea0_0           conda-forge
  libiconv                   1.17          h166bdaf_0           conda-forge
  libjpeg-turbo              3.0.0         hd590300_1           conda-forge
  liblapack                  3.9.0         20_linux64_openblas  conda-forge
  liblapacke                 3.9.0         20_linux64_openblas  conda-forge
  libnghttp2                 1.58.0        h47da74e_0           conda-forge
  libnsl                     2.0.1         hd590300_0           conda-forge
  libopenblas                0.3.25        pthreads_h413a1c8_0  conda-forge
  libpng                     1.6.39        h753d276_0           conda-forge
  libsqlite                  3.44.2        h2797004_0           conda-forge
  libssh2                    1.11.0        h0841786_0           conda-forge
  libstdcxx-ng               13.2.0        h7e041cc_3           conda-forge
  libtiff                    4.6.0         ha9c0a0a_2           conda-forge
  libuuid                    2.38.1        h0b41bf4_0           conda-forge
  libwebp                    1.3.2         h658648e_1           conda-forge
  libwebp-base               1.3.2         hd590300_0           conda-forge
  libxml2                    2.12.2        h232c23b_0           conda-forge
  libzlib                    1.2.13        hd590300_5           conda-forge
  linbox                     1.6.3         h9d78c56_7           conda-forge
  lrcalc                     2.1           h27087fc_5           conda-forge
  m4ri                       20140914      h7ca028e_1005        conda-forge
  m4rie                      20150908      h7ca028e_1001        conda-forge
  markupsafe                 2.1.3         py310h2372a71_1      conda-forge
  matplotlib-inline          0.1.6         pyhd8ed1ab_0         conda-forge
  maxima                     5.47.0        hed6455c_0           conda-forge
  memory-allocator           0.1.3         py310h2372a71_0      conda-forge
  mpc                        1.3.1         hfe3b2da_0           conda-forge
  mpfi                       1.5.4         h9f54685_1001        conda-forge
  mpfr                       4.2.1         h9458935_0           conda-forge
  mpmath                     1.3.0         pyhd8ed1ab_0         conda-forge
  nauty                      2.8.8         hd590300_0           conda-forge
  ncurses                    6.4           h59595ed_2           conda-forge
  ntl                        11.4.3        hef3c4d3_1           conda-forge
  numpy                      1.26.2        py310hb13e2d6_0      conda-forge
  openssl                    3.2.0         hd590300_1           conda-forge
  pari                       2.13.3        he2feae2_1_pthread   conda-forge
  pari-galdata               0.0.20180411  0                    conda-forge
  pari-seadata-small         0.0.20090618  0                    conda-forge
  parso                      0.8.3         pyhd8ed1ab_0         conda-forge
  perl                       5.32.1        4_hd590300_perl5     conda-forge
  pexpect                    4.8.0         pyh1a96a4e_2         conda-forge
  pickleshare                0.7.5         py_1003              conda-forge
  pip                        23.3.1        pyhd8ed1ab_0         conda-forge
  planarity                  3.0.0.5       h36c2ea0_1002        conda-forge
  ppl                        1.2           h6ec01c2_1006        conda-forge
  pplpy                      0.8.9         py310h28f6eb6_0      conda-forge
  primecount                 7.9           hcb278e6_0           conda-forge
  primecountpy               0.1.0         py310hd41b1e2_4      conda-forge
  primesieve                 11.1          h59595ed_0           conda-forge
  prompt-toolkit             3.0.41        pyha770c72_0         conda-forge
  psutil                     5.9.5         py310h2372a71_1      conda-forge
  ptyprocess                 0.7.0         pyhd3deb0d_0         conda-forge
  pygments                   2.17.2        pyhd8ed1ab_0         conda-forge
  python                     3.10.13       hd12c33a_0_cpython   conda-forge
  python-lrcalc              2.1           py310hd8f1fbe_5      conda-forge
  python_abi                 3.10          4_cp310              conda-forge
  ratpoints                  2.1.3         h445213a_1002        conda-forge
  readline                   8.2           h8228510_1           conda-forge
  rw                         0.9           hd590300_1           conda-forge
  sagelib                    9.6           py310h28be7dd_4      conda-forge
  setuptools                 68.2.2        pyhd8ed1ab_0         conda-forge
  singular                   4.2.1.p3      h1ea75ed_2           conda-forge
  six                        1.16.0        pyh6c4a22f_0         conda-forge
  symmetrica                 2.0           h58526e2_1007        conda-forge
  sympy                      1.12          pypyh9d50eac_103     conda-forge
  three.js                   122           hd8ed1ab_2           conda-forge
  threejs-sage               122           hd8ed1ab_2           conda-forge
  tk                         8.6.13        noxft_h4845f30_101   conda-forge
  traitlets                  5.14.0        pyhd8ed1ab_0         conda-forge
  tzdata                     2023c         h71feb2d_0           conda-forge
  wcwidth                    0.2.12        pyhd8ed1ab_0         conda-forge
  wheel                      0.42.0        pyhd8ed1ab_0         conda-forge
  widgetsnbextension         4.0.9         pyhd8ed1ab_0         conda-forge
  xz                         5.2.6         h166bdaf_0           conda-forge
  zlib                       1.2.13        hd590300_5           conda-forge
  zn_poly                    0.9.2         h9202a9a_0           conda-forge
  zstd                       1.5.5         hfc55251_0           conda-forge
```

### Environment info

```shell
libmamba version : 1.5.1
     micromamba version : 1.5.1
           curl version : libcurl/8.4.0 OpenSSL/3.1.4 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /home/vincent/micromamba/envs
          package cache : /home/vincent/micromamba/pkgs
                          /home/vincent/.mamba/pkgs
            environment : test (active)
           env location : /home/vincent/micromamba/envs/test
      user config files : /home/vincent/.mambarc
 populated config files : /home/vincent/.condarc
       virtual packages : __unix=0=0
                          __linux=6.6.4=0
                          __glibc=2.38=0
                          __archspec=1=x86_64
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : /home/vincent/micromamba
               platform : linux-64
```

**Comment by videlec** [comment]
NOTE: It works fine adding `maxima<5.47.0`

**Comment by saraedum** [comment]
Also, 10.0 breaks with 5.47.0.
